apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        env: 
        - name: "MYSQL_ROOT_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: db-config
              key:  MYSQL_ROOT_PASSWORD
        - name: "MYSQL_DATABASE"
          valueFrom:
            secretKeyRef:
              name: db-config
              key:  MYSQL_DATABASE
