apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: backend
  newName: mattedamo26/first-attempt-test
  newTag: latest
kind: Kustomization
namespace: first-attempt-test
patches:
- path: backend_backend_patch.yaml
  target:
    labelSelector: tier=backend
    name: backend
patchesStrategicMerge: null
resources:
- ../../base
secretGenerator:
- literals:
  - MYSQL_ROOT_PASSWORD=password
  - MYSQL_DATABASE=test
  name: db-config
