apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base/
images:
- name: backend
  newName: mattedamo26/first-attempt
  newTag: latest
kind: Kustomization
namespace: first-attempt-prod
secretGenerator:
- literals:
  - MYSQL_ROOT_PASSWORD=password
  - MYSQL_DATABASE=thesisAppMariadb
  name: db-config
