apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels: 
    app: thesis-app
    tier: frontend
spec:
  selector:
    matchLabels:
      app: thesis-app
      tier: frontend
  template:
    metadata:
      labels:
        app: thesis-app
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: "mattedamo26/first-attempt-frontend"
        imagePullPolicy: Always        
        ports:
          - containerPort: 80
