apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels: 
    app: thesis-app
    tier: frontend
spec:
  selector:
    app: thesis-app
    tier: frontend
  ports:
  - protocol: TCP
    port: 4200
    nodePort: 32731
    targetPort: 80
  type: LoadBalancer
