apiVersion: v1
kind: Service
metadata: 
  name: backend
  labels:
    app: thesis-app
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: thesis-app
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
