apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: first-attempt-dev


images:
- name: backend
  newName: mattedamo26/first-attempt-dev
  newTag: latest

secretGenerator:
- name: db-config
  literals:
  - MYSQL_ROOT_PASSWORD=password
  - MYSQL_DATABASE=dev
