name: run-py-script

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: set environment variables
        uses: allenevans/set-env@v2.0.0
        with:
          NS: 'prova'
      
      - name: Check out code
        uses: actions/checkout@v2
    
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: "3.x"
      - run: pip install PyYAML
      - run: python set-ns.py
      - run: cat file.yaml
    
